import React from "react";

function Terms() {
  return (
    <div style={{ padding: "20px", lineHeight: "1.6", fontFamily: "Arial, sans-serif" }}>
      <h1>Terms and Conditions</h1>

      <p>This document is an electronic record in terms of Information Technology Act, 2000 and rules thereunder. 
      This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>

      <p>The Platform is owned by <strong>Smart Students Classes</strong>, with its registered office at Behind Girls College, Morar, Madhya Pradesh, India.</p>

      <h2>1. Acceptance of Terms</h2>
      <p>By accessing or using our Platform, you agree to be bound by these Terms of Use and all applicable policies. 
      If you transact on the Platform, you shall be subject to the applicable policies for such transactions.</p>

      <h2>2. User Responsibilities</h2>
      <p>To access and use the Services, you agree to provide true, accurate, and complete information during registration. 
      You are responsible for all activities done through your account.</p>

      <h2>3. Disclaimer</h2>
      <p>We do not guarantee the accuracy, completeness, or suitability of the information and materials provided on the Platform. 
      All use is at your own risk.</p>

      <h2>4. Intellectual Property</h2>
      <p>All contents of the Platform are proprietary to us. Unauthorized use may lead to legal action.</p>

      <h2>5. Payments</h2>
      <p>You agree to pay the charges associated with availing the Services. Platform Owner is not liable for any misuse.</p>

      <h2>6. Links to Third-Party Websites</h2>
      <p>The Platform may contain links to third-party websites. Your use of such websites is governed by their respective terms and privacy policies.</p>

      <h2>7. Indemnification</h2>
      <p>You agree to indemnify and hold harmless Smart Students Classes, its affiliates, and employees from any claims or actions arising out of your use of the Platform.</p>

      <h2>8. Force Majeure</h2>
      <p>Smart Students Classes shall not be liable for delays or failures caused by events beyond reasonable control.</p>

      <h2>9. Governing Law</h2>
      <p>These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of Indian courts.</p>
    </div>
  );
}

export default Terms;
